<Type Name="FirstChanceExceptionEventArgs" FullName="System.Runtime.ExceptionServices.FirstChanceExceptionEventArgs">
  <TypeSignature Language="C#" Value="public class FirstChanceExceptionEventArgs : EventArgs" />
  <TypeSignature Language="ILAsm" Value=".class public auto ansi beforefieldinit FirstChanceExceptionEventArgs extends System.EventArgs" />
  <TypeSignature Language="DocId" Value="T:System.Runtime.ExceptionServices.FirstChanceExceptionEventArgs" />
  <TypeSignature Language="VB.NET" Value="Public Class FirstChanceExceptionEventArgs&#xA;Inherits EventArgs" />
  <TypeSignature Language="C++ CLI" Value="public ref class FirstChanceExceptionEventArgs : EventArgs" />
  <AssemblyInfo>
    <AssemblyName>mscorlib</AssemblyName>
    <AssemblyVersion>2.0.5.0</AssemblyVersion>
    <AssemblyVersion>4.0.0.0</AssemblyVersion>
  </AssemblyInfo>
  <AssemblyInfo>
    <AssemblyName>netstandard</AssemblyName>
    <AssemblyVersion>2.0.0.0</AssemblyVersion>
  </AssemblyInfo>
  <AssemblyInfo>
    <AssemblyName>System.Runtime</AssemblyName>
    <AssemblyVersion>4.2.0.0</AssemblyVersion>
    <AssemblyVersion>4.2.1.0</AssemblyVersion>
  </AssemblyInfo>
  <Base>
    <BaseTypeName>System.EventArgs</BaseTypeName>
  </Base>
  <Interfaces />
  <Docs>
    <summary><span data-ttu-id="92803-101">Stellt Daten für das Benachrichtigungsereignis bereit, das beim erstmaligen Auftreten einer verwalteten Ausnahme ausgelöst wird, bevor die Common Language Runtime beginnt, nach Ereignishandlern zu suchen.</span><span class="sxs-lookup"><span data-stu-id="92803-101">Provides data for the notification event that is raised when a managed exception first occurs, before the common language runtime begins searching for event handlers.</span></span></summary>
    <remarks>
      <format type="text/markdown"><![CDATA[  
  
## Remarks  
 <span data-ttu-id="92803-102">Diese Klasse stellt den Ausnahmehandler für die <xref:System.AppDomain.FirstChanceException?displayProperty=nameWithType> Ereignis "mit" Zugriff auf die Ausnahme.</span><span class="sxs-lookup"><span data-stu-id="92803-102">This class provides the exception handler for the <xref:System.AppDomain.FirstChanceException?displayProperty=nameWithType> event with access to the exception.</span></span>  
  
   
  
## Examples  
 <span data-ttu-id="92803-103">Das folgende Beispiel erstellt eine Reihe von Anwendungsdomänen, die mit dem Namen `Child_0` über `Child_3`, mit einem `Worker` Objekt pro Anwendungsdomäne.</span><span class="sxs-lookup"><span data-stu-id="92803-103">The following example creates a series of application domains named `Child_0` through `Child_3`, with a `Worker` object in each application domain.</span></span> <span data-ttu-id="92803-104">Jede `Worker` Objekt enthält einen Verweis auf die `Worker` -Objekt in der nächsten Anwendungsdomäne, außer für die `Worker` in der letzten Anwendungsdomäne.</span><span class="sxs-lookup"><span data-stu-id="92803-104">Each `Worker` object has a reference to the `Worker` object in the next application domain, except for the `Worker` in the last application domain.</span></span> <span data-ttu-id="92803-105">Die <xref:System.AppDomain.FirstChanceException> Ereignis behandelt wird, in allen Anwendungsdomänen außer `Child_1`.</span><span class="sxs-lookup"><span data-stu-id="92803-105">The <xref:System.AppDomain.FirstChanceException> event is handled in all application domains except `Child_1`.</span></span>  
  
 <span data-ttu-id="92803-106">Wenn die Anwendungsdomänen erstellt wurden, ruft die Standardanwendungsdomäne die `TestException` Methode für die erste untergeordnete Anwendungsdomäne.</span><span class="sxs-lookup"><span data-stu-id="92803-106">When the application domains have been created, the default application domain calls the `TestException` method for the first child application domain.</span></span> <span data-ttu-id="92803-107">Jede `Worker` -Objekt ruft die `TestException` Methode für die nächsten, bis der letzte `Worker` löst eine Ausnahme, die entweder behandelt oder nicht behandelt wird.</span><span class="sxs-lookup"><span data-stu-id="92803-107">Each `Worker` object calls the `TestException` method for the next, until the last `Worker` throws an exception that is either handled or unhandled.</span></span> <span data-ttu-id="92803-108">Folglich alle Anwendungsdomänen, der aktuelle Thread durchläuft und `TestException` wird dem Stapel in jeder Anwendungsdomäne hinzugefügt.</span><span class="sxs-lookup"><span data-stu-id="92803-108">Thus, the current thread passes through all the application domains, and `TestException` is added to the stack in each application domain.</span></span>  
  
 <span data-ttu-id="92803-109">Wenn der letzte `Worker` Objekt verarbeitet die Ausnahme, die <xref:System.AppDomain.FirstChanceException> Ereignis wird nur in der letzten Anwendungsdomäne.</span><span class="sxs-lookup"><span data-stu-id="92803-109">When the last `Worker` object handles the exception, the <xref:System.AppDomain.FirstChanceException> event is raised only in the last application domain.</span></span> <span data-ttu-id="92803-110">Die anderen Anwendungsdomänen Gelegenheit nie zur Behandlung von Ausnahmen, damit das Ereignis nicht ausgelöst wird.</span><span class="sxs-lookup"><span data-stu-id="92803-110">The other application domains never get a chance to handle the exception, so the event is not raised.</span></span>  
  
 <span data-ttu-id="92803-111">Bei der letzten `Worker` Objekt behandelt die Ausnahme nicht die <xref:System.AppDomain.FirstChanceException> Ereignis wird in jeder Anwendungsdomäne, die einen Ereignishandler aufweist.</span><span class="sxs-lookup"><span data-stu-id="92803-111">When the last `Worker` object does not handle the exception, the <xref:System.AppDomain.FirstChanceException> event is raised in each application domain that has an event handler.</span></span> <span data-ttu-id="92803-112">Nach Abschluss der einzelnen Ereignishandler wird der Stapel entladen, bis die Ausnahme durch die Standardanwendungsdomäne abgefangen wird fortgesetzt.</span><span class="sxs-lookup"><span data-stu-id="92803-112">After each event handler has finished, the stack continues to unwind until the exception is caught by the default application domain.</span></span>  
  
> [!NOTE]
>  <span data-ttu-id="92803-113">Um anzuzeigen, wie die Anzeige der Stapel vergrößert wird, wie das Ereignis, das näher ausgelöst wird und näher an die Standardanwendungsdomäne, ändern Sie `e.Exception.Message` auf `e.Exception` in der `FirstChanceHandler` -Ereignishandler.</span><span class="sxs-lookup"><span data-stu-id="92803-113">To see how the stack display grows as the event is raised closer and closer to the default application domain, change `e.Exception.Message` to `e.Exception` in the `FirstChanceHandler` event handlers.</span></span> <span data-ttu-id="92803-114">Beachten Sie, dass bei `TestException` heißt über Anwendungsdomänengrenzen hinweg, dann zweimal angezeigt: einmal für den Proxy und einmal für den Stub.</span><span class="sxs-lookup"><span data-stu-id="92803-114">Notice that when `TestException` is called across application domain boundaries, it appears twice: once for the proxy and once for the stub.</span></span>  
  
 [!code-csharp[System.AppDomain.FirstChanceException#1](~/samples/snippets/csharp/VS_Snippets_CLR_System/system.appdomain.firstchanceexception/cs/example.cs#1)]
 [!code-vb[System.AppDomain.FirstChanceException#1](~/samples/snippets/visualbasic/VS_Snippets_CLR_System/system.appdomain.firstchanceexception/vb/example.vb#1)]  
  
 ]]></format>
    </remarks>
    <altmember cref="E:System.AppDomain.FirstChanceException" />
  </Docs>
  <Members>
    <Member MemberName=".ctor">
      <MemberSignature Language="C#" Value="public FirstChanceExceptionEventArgs (Exception exception);" />
      <MemberSignature Language="ILAsm" Value=".method public hidebysig specialname rtspecialname instance void .ctor(class System.Exception exception) cil managed" />
      <MemberSignature Language="DocId" Value="M:System.Runtime.ExceptionServices.FirstChanceExceptionEventArgs.#ctor(System.Exception)" />
      <MemberSignature Language="C++ CLI" Value="public:&#xA; FirstChanceExceptionEventArgs(Exception ^ exception);" />
      <MemberType>Constructor</MemberType>
      <AssemblyInfo>
        <AssemblyName>mscorlib</AssemblyName>
        <AssemblyVersion>2.0.5.0</AssemblyVersion>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <AssemblyInfo>
        <AssemblyName>netstandard</AssemblyName>
        <AssemblyVersion>2.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <AssemblyInfo>
        <AssemblyName>System.Runtime</AssemblyName>
        <AssemblyVersion>4.2.0.0</AssemblyVersion>
        <AssemblyVersion>4.2.1.0</AssemblyVersion>
      </AssemblyInfo>
      <Parameters>
        <Parameter Name="exception" Type="System.Exception" />
      </Parameters>
      <Docs>
        <param name="exception"><span data-ttu-id="92803-115">Die Ausnahme, die gerade von verwaltetem Code ausgelöst wurde und die vom <see cref="E:System.AppDomain.UnhandledException" />-Ereignis untersucht wird.</span><span class="sxs-lookup"><span data-stu-id="92803-115">The exception that was just thrown by managed code, and that will be examined by the <see cref="E:System.AppDomain.UnhandledException" /> event.</span></span></param>
        <summary><span data-ttu-id="92803-116">Initialisiert eine neue Instanz der <see cref="T:System.Runtime.ExceptionServices.FirstChanceExceptionEventArgs" />-Klasse mit einer angegebenen Ausnahme.</span><span class="sxs-lookup"><span data-stu-id="92803-116">Initializes a new instance of the <see cref="T:System.Runtime.ExceptionServices.FirstChanceExceptionEventArgs" /> class with a specified exception.</span></span></summary>
        <remarks>
          <format type="text/markdown"><![CDATA[  
  
## Remarks  
 <span data-ttu-id="92803-117">Dieser Konstruktor wird von der common Language Runtime nicht von Anwendungscode aufgerufen.</span><span class="sxs-lookup"><span data-stu-id="92803-117">This constructor is called by the common language runtime, not by application code.</span></span>  
  
 ]]></format>
        </remarks>
      </Docs>
    </Member>
    <Member MemberName="Exception">
      <MemberSignature Language="C#" Value="public Exception Exception { get; }" />
      <MemberSignature Language="ILAsm" Value=".property instance class System.Exception Exception" />
      <MemberSignature Language="DocId" Value="P:System.Runtime.ExceptionServices.FirstChanceExceptionEventArgs.Exception" />
      <MemberSignature Language="VB.NET" Value="Public ReadOnly Property Exception As Exception" />
      <MemberSignature Language="C++ CLI" Value="public:&#xA; property Exception ^ Exception { Exception ^ get(); };" />
      <MemberType>Property</MemberType>
      <AssemblyInfo>
        <AssemblyName>mscorlib</AssemblyName>
        <AssemblyVersion>2.0.5.0</AssemblyVersion>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <AssemblyInfo>
        <AssemblyName>netstandard</AssemblyName>
        <AssemblyVersion>2.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <AssemblyInfo>
        <AssemblyName>System.Runtime</AssemblyName>
        <AssemblyVersion>4.2.0.0</AssemblyVersion>
        <AssemblyVersion>4.2.1.0</AssemblyVersion>
      </AssemblyInfo>
      <Attributes>
        <Attribute>
          <AttributeName>get: System.Runtime.ConstrainedExecution.ReliabilityContract(System.Runtime.ConstrainedExecution.Consistency.WillNotCorruptState, System.Runtime.ConstrainedExecution.Cer.Success)</AttributeName>
        </Attribute>
      </Attributes>
      <ReturnValue>
        <ReturnType>System.Exception</ReturnType>
      </ReturnValue>
      <Docs>
        <summary><span data-ttu-id="92803-118">Das verwaltete Ausnahmeobjekt, das der ausgelösten Ausnahme in verwaltetem Code entspricht.</span><span class="sxs-lookup"><span data-stu-id="92803-118">The managed exception object that corresponds to the exception thrown in managed code.</span></span></summary>
        <value><span data-ttu-id="92803-119">Die gerade ausgelöste Ausnahme.</span><span class="sxs-lookup"><span data-stu-id="92803-119">The newly thrown exception.</span></span></value>
        <remarks>
          <format type="text/markdown"><![CDATA[  
  
## Remarks  
 <span data-ttu-id="92803-120">Die Methode, verarbeitet die <xref:System.AppDomain.UnhandledException?displayProperty=nameWithType> Ereignis kann die Ausnahme untersuchen und eine entsprechende Protokollierung oder andere Notification Services ausführen.</span><span class="sxs-lookup"><span data-stu-id="92803-120">The method that handles the <xref:System.AppDomain.UnhandledException?displayProperty=nameWithType> event can examine the exception and perform appropriate logging or other notification services.</span></span>  
  
 <span data-ttu-id="92803-121">Beispielcode finden Sie unter <xref:System.Runtime.ExceptionServices.FirstChanceExceptionEventArgs>.</span><span class="sxs-lookup"><span data-stu-id="92803-121">For example code, see <xref:System.Runtime.ExceptionServices.FirstChanceExceptionEventArgs>.</span></span>  
  
 ]]></format>
        </remarks>
      </Docs>
    </Member>
  </Members>
</Type>