<Type Name="FirstChanceExceptionEventArgs" FullName="System.Runtime.ExceptionServices.FirstChanceExceptionEventArgs">
  <Metadata><Meta Name="ms.openlocfilehash" Value="169bae8320df5ccab499f54dc4a4009bcb8b6dfc" /><Meta Name="ms.sourcegitcommit" Value="055a4a82a0b08bfbdc21bd1347fb71f7fe2c099e" /><Meta Name="ms.translationtype" Value="MT" /><Meta Name="ms.contentlocale" Value="de-DE" /><Meta Name="ms.lasthandoff" Value="08/15/2019" /><Meta Name="ms.locfileid" Value="69271890" /></Metadata><TypeSignature Language="C#" Value="public class FirstChanceExceptionEventArgs : EventArgs" />
  <TypeSignature Language="ILAsm" Value=".class public auto ansi beforefieldinit FirstChanceExceptionEventArgs extends System.EventArgs" />
  <TypeSignature Language="DocId" Value="T:System.Runtime.ExceptionServices.FirstChanceExceptionEventArgs" />
  <TypeSignature Language="VB.NET" Value="Public Class FirstChanceExceptionEventArgs&#xA;Inherits EventArgs" />
  <TypeSignature Language="C++ CLI" Value="public ref class FirstChanceExceptionEventArgs : EventArgs" />
  <TypeSignature Language="F#" Value="type FirstChanceExceptionEventArgs = class&#xA;    inherit EventArgs" />
  <AssemblyInfo>
    <AssemblyName>mscorlib</AssemblyName>
    <AssemblyVersion>2.0.5.0</AssemblyVersion>
    <AssemblyVersion>4.0.0.0</AssemblyVersion>
  </AssemblyInfo>
  <AssemblyInfo>
    <AssemblyName>netstandard</AssemblyName>
    <AssemblyVersion>2.0.0.0</AssemblyVersion>
    <AssemblyVersion>2.1.0.0</AssemblyVersion>
  </AssemblyInfo>
  <AssemblyInfo>
    <AssemblyName>System.Runtime</AssemblyName>
    <AssemblyVersion>4.2.0.0</AssemblyVersion>
    <AssemblyVersion>4.2.1.0</AssemblyVersion>
  </AssemblyInfo>
  <Base>
    <BaseTypeName>System.EventArgs</BaseTypeName>
  </Base>
  <Interfaces />
  <Docs>
    <summary><span data-ttu-id="d02c9-101">Stellt Daten für das Benachrichtigungsereignis bereit, das beim erstmaligen Auftreten einer verwalteten Ausnahme ausgelöst wird, bevor die Common Language Runtime beginnt, nach Ereignishandlern zu suchen.</span><span class="sxs-lookup"><span data-stu-id="d02c9-101">Provides data for the notification event that is raised when a managed exception first occurs, before the common language runtime begins searching for event handlers.</span></span></summary>
    <remarks>
      <format type="text/markdown"><![CDATA[  
  
## Remarks  
 <span data-ttu-id="d02c9-102">Diese Klasse stellt den Ausnahmehandler für das <xref:System.AppDomain.FirstChanceException?displayProperty=nameWithType> -Ereignis bereit, das Zugriff auf die Ausnahme hat.</span><span class="sxs-lookup"><span data-stu-id="d02c9-102">This class provides the exception handler for the <xref:System.AppDomain.FirstChanceException?displayProperty=nameWithType> event with access to the exception.</span></span>  
  
   
  
## Examples  
 <span data-ttu-id="d02c9-103">Im folgenden Beispiel wird eine Reihe von Anwendungs Domänen `Child_0` , `Child_3`die durch benannt `Worker` sind, mit einem-Objekt in jeder Anwendungsdomäne erstellt.</span><span class="sxs-lookup"><span data-stu-id="d02c9-103">The following example creates a series of application domains named `Child_0` through `Child_3`, with a `Worker` object in each application domain.</span></span> <span data-ttu-id="d02c9-104">Jedes `Worker` -Objekt verfügt über einen Verweis `Worker` auf das-Objekt in der nächsten Anwendungsdomäne, `Worker` mit Ausnahme der in der letzten Anwendungsdomäne.</span><span class="sxs-lookup"><span data-stu-id="d02c9-104">Each `Worker` object has a reference to the `Worker` object in the next application domain, except for the `Worker` in the last application domain.</span></span> <span data-ttu-id="d02c9-105">Das <xref:System.AppDomain.FirstChanceException> Ereignis wird in allen Anwendungs Domänen außer `Child_1`behandelt.</span><span class="sxs-lookup"><span data-stu-id="d02c9-105">The <xref:System.AppDomain.FirstChanceException> event is handled in all application domains except `Child_1`.</span></span>  
  
 <span data-ttu-id="d02c9-106">Wenn die Anwendungs Domänen erstellt wurden, ruft die Standard Anwendungsdomäne die `TestException` -Methode für die erste untergeordnete Anwendungsdomäne auf.</span><span class="sxs-lookup"><span data-stu-id="d02c9-106">When the application domains have been created, the default application domain calls the `TestException` method for the first child application domain.</span></span> <span data-ttu-id="d02c9-107">Jedes `Worker` -Objekt ruft `TestException` die-Methode für den nächsten auf, `Worker` bis der letzte eine Ausnahme auslöst, die entweder behandelt oder nicht behandelt wird.</span><span class="sxs-lookup"><span data-stu-id="d02c9-107">Each `Worker` object calls the `TestException` method for the next, until the last `Worker` throws an exception that is either handled or unhandled.</span></span> <span data-ttu-id="d02c9-108">Folglich durchläuft der aktuelle Thread alle Anwendungs Domänen und `TestException` wird dem Stapel in den einzelnen Anwendungs Domänen hinzugefügt.</span><span class="sxs-lookup"><span data-stu-id="d02c9-108">Thus, the current thread passes through all the application domains, and `TestException` is added to the stack in each application domain.</span></span>  
  
 <span data-ttu-id="d02c9-109">Wenn das letzte `Worker` Objekt die Ausnahme behandelt, wird <xref:System.AppDomain.FirstChanceException> das Ereignis nur in der letzten Anwendungsdomäne ausgelöst.</span><span class="sxs-lookup"><span data-stu-id="d02c9-109">When the last `Worker` object handles the exception, the <xref:System.AppDomain.FirstChanceException> event is raised only in the last application domain.</span></span> <span data-ttu-id="d02c9-110">Die anderen Anwendungs Domänen erhalten nie die Möglichkeit, die Ausnahme zu behandeln, sodass das Ereignis nicht ausgelöst wird.</span><span class="sxs-lookup"><span data-stu-id="d02c9-110">The other application domains never get a chance to handle the exception, so the event is not raised.</span></span>  
  
 <span data-ttu-id="d02c9-111">Wenn das letzte `Worker` Objekt die Ausnahme nicht behandelt, wird das <xref:System.AppDomain.FirstChanceException> -Ereignis in jeder Anwendungsdomäne ausgelöst, die über einen Ereignishandler verfügt.</span><span class="sxs-lookup"><span data-stu-id="d02c9-111">When the last `Worker` object does not handle the exception, the <xref:System.AppDomain.FirstChanceException> event is raised in each application domain that has an event handler.</span></span> <span data-ttu-id="d02c9-112">Nachdem jeder Ereignishandler beendet wurde, wird der Stapel fortgesetzt, bis die Ausnahme von der Standard Anwendungsdomäne abgefangen wird.</span><span class="sxs-lookup"><span data-stu-id="d02c9-112">After each event handler has finished, the stack continues to unwind until the exception is caught by the default application domain.</span></span>  
  
> [!NOTE]
>  <span data-ttu-id="d02c9-113">Ändern `e.Exception.Message` Sie `e.Exception` in den`FirstChanceHandler` Ereignis Handlern in, um zu sehen, wie die Stapel Anzeige zunimmt, wenn das Ereignis näher und näher an der Standard Anwendungsdomäne ausgelöst wird.</span><span class="sxs-lookup"><span data-stu-id="d02c9-113">To see how the stack display grows as the event is raised closer and closer to the default application domain, change `e.Exception.Message` to `e.Exception` in the `FirstChanceHandler` event handlers.</span></span> <span data-ttu-id="d02c9-114">Beachten Sie Folgendes `TestException` : Wenn über Anwendungs Domänen Grenzen hinweg aufgerufen wird, wird er zweimal angezeigt: einmal für den Proxy und einmal für den Stub.</span><span class="sxs-lookup"><span data-stu-id="d02c9-114">Notice that when `TestException` is called across application domain boundaries, it appears twice: once for the proxy and once for the stub.</span></span>  
  
 [!code-csharp[System.AppDomain.FirstChanceException#1](~/samples/snippets/csharp/VS_Snippets_CLR_System/system.appdomain.firstchanceexception/cs/example.cs#1)]
 [!code-vb[System.AppDomain.FirstChanceException#1](~/samples/snippets/visualbasic/VS_Snippets_CLR_System/system.appdomain.firstchanceexception/vb/example.vb#1)]  
  
 ]]></format>
    </remarks>
    <altmember cref="E:System.AppDomain.FirstChanceException" />
  </Docs>
  <Members>
    <Member MemberName=".ctor">
      <MemberSignature Language="C#" Value="public FirstChanceExceptionEventArgs (Exception exception);" />
      <MemberSignature Language="ILAsm" Value=".method public hidebysig specialname rtspecialname instance void .ctor(class System.Exception exception) cil managed" />
      <MemberSignature Language="DocId" Value="M:System.Runtime.ExceptionServices.FirstChanceExceptionEventArgs.#ctor(System.Exception)" />
      <MemberSignature Language="C++ CLI" Value="public:&#xA; FirstChanceExceptionEventArgs(Exception ^ exception);" />
      <MemberSignature Language="F#" Value="new System.Runtime.ExceptionServices.FirstChanceExceptionEventArgs : Exception -&gt; System.Runtime.ExceptionServices.FirstChanceExceptionEventArgs" Usage="new System.Runtime.ExceptionServices.FirstChanceExceptionEventArgs exception" />
      <MemberType>Constructor</MemberType>
      <AssemblyInfo>
        <AssemblyName>mscorlib</AssemblyName>
        <AssemblyVersion>2.0.5.0</AssemblyVersion>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <AssemblyInfo>
        <AssemblyName>netstandard</AssemblyName>
        <AssemblyVersion>2.0.0.0</AssemblyVersion>
        <AssemblyVersion>2.1.0.0</AssemblyVersion>
      </AssemblyInfo>
      <AssemblyInfo>
        <AssemblyName>System.Runtime</AssemblyName>
        <AssemblyVersion>4.2.0.0</AssemblyVersion>
        <AssemblyVersion>4.2.1.0</AssemblyVersion>
      </AssemblyInfo>
      <Parameters>
        <Parameter Name="exception" Type="System.Exception" />
      </Parameters>
      <Docs>
        <param name="exception"><span data-ttu-id="d02c9-115">Die Ausnahme, die gerade von verwaltetem Code ausgelöst wurde und die vom <see cref="E:System.AppDomain.UnhandledException" />-Ereignis untersucht wird.</span><span class="sxs-lookup"><span data-stu-id="d02c9-115">The exception that was just thrown by managed code, and that will be examined by the <see cref="E:System.AppDomain.UnhandledException" /> event.</span></span></param>
        <summary><span data-ttu-id="d02c9-116">Initialisiert eine neue Instanz der <see cref="T:System.Runtime.ExceptionServices.FirstChanceExceptionEventArgs" />-Klasse mit einer angegebenen Ausnahme.</span><span class="sxs-lookup"><span data-stu-id="d02c9-116">Initializes a new instance of the <see cref="T:System.Runtime.ExceptionServices.FirstChanceExceptionEventArgs" /> class with a specified exception.</span></span></summary>
        <remarks>
          <format type="text/markdown"><![CDATA[  
  
## Remarks  
 <span data-ttu-id="d02c9-117">Dieser Konstruktor wird vom Common Language Runtime und nicht vom Anwendungscode aufgerufen.</span><span class="sxs-lookup"><span data-stu-id="d02c9-117">This constructor is called by the common language runtime, not by application code.</span></span>  
  
 ]]></format>
        </remarks>
      </Docs>
    </Member>
    <Member MemberName="Exception">
      <MemberSignature Language="C#" Value="public Exception Exception { get; }" />
      <MemberSignature Language="ILAsm" Value=".property instance class System.Exception Exception" />
      <MemberSignature Language="DocId" Value="P:System.Runtime.ExceptionServices.FirstChanceExceptionEventArgs.Exception" />
      <MemberSignature Language="VB.NET" Value="Public ReadOnly Property Exception As Exception" />
      <MemberSignature Language="C++ CLI" Value="public:&#xA; property Exception ^ Exception { Exception ^ get(); };" />
      <MemberSignature Language="F#" Value="member this.Exception : Exception" Usage="System.Runtime.ExceptionServices.FirstChanceExceptionEventArgs.Exception" />
      <MemberType>Property</MemberType>
      <AssemblyInfo>
        <AssemblyName>mscorlib</AssemblyName>
        <AssemblyVersion>2.0.5.0</AssemblyVersion>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <AssemblyInfo>
        <AssemblyName>netstandard</AssemblyName>
        <AssemblyVersion>2.0.0.0</AssemblyVersion>
        <AssemblyVersion>2.1.0.0</AssemblyVersion>
      </AssemblyInfo>
      <AssemblyInfo>
        <AssemblyName>System.Runtime</AssemblyName>
        <AssemblyVersion>4.2.0.0</AssemblyVersion>
        <AssemblyVersion>4.2.1.0</AssemblyVersion>
      </AssemblyInfo>
      <Attributes>
        <Attribute FrameworkAlternate="netframework-4.0;netframework-4.5;netframework-4.5.1;netframework-4.5.2;netframework-4.6;netframework-4.6.1;netframework-4.6.2;netframework-4.7;netframework-4.7.1;netframework-4.7.2;xamarinandroid-7.1;xamarinios-10.8;xamarinmac-3.0;netframework-4.8">
          <AttributeName>get: System.Runtime.ConstrainedExecution.ReliabilityContract(System.Runtime.ConstrainedExecution.Consistency.WillNotCorruptState, System.Runtime.ConstrainedExecution.Cer.Success)</AttributeName>
        </Attribute>
      </Attributes>
      <ReturnValue>
        <ReturnType>System.Exception</ReturnType>
      </ReturnValue>
      <Docs>
        <summary><span data-ttu-id="d02c9-118">Das verwaltete Ausnahmeobjekt, das der ausgelösten Ausnahme in verwaltetem Code entspricht.</span><span class="sxs-lookup"><span data-stu-id="d02c9-118">The managed exception object that corresponds to the exception thrown in managed code.</span></span></summary>
        <value><span data-ttu-id="d02c9-119">Die gerade ausgelöste Ausnahme.</span><span class="sxs-lookup"><span data-stu-id="d02c9-119">The newly thrown exception.</span></span></value>
        <remarks>
          <format type="text/markdown"><![CDATA[  
  
## Remarks  
 <span data-ttu-id="d02c9-120">Die Methode, die das <xref:System.AppDomain.UnhandledException?displayProperty=nameWithType> Ereignis behandelt, kann die Ausnahme untersuchen und die entsprechende Protokollierung oder andere Benachrichtigungsdienste durchführen.</span><span class="sxs-lookup"><span data-stu-id="d02c9-120">The method that handles the <xref:System.AppDomain.UnhandledException?displayProperty=nameWithType> event can examine the exception and perform appropriate logging or other notification services.</span></span>  
  
 <span data-ttu-id="d02c9-121">Beispielcode finden Sie unter <xref:System.Runtime.ExceptionServices.FirstChanceExceptionEventArgs>.</span><span class="sxs-lookup"><span data-stu-id="d02c9-121">For example code, see <xref:System.Runtime.ExceptionServices.FirstChanceExceptionEventArgs>.</span></span>  
  
 ]]></format>
        </remarks>
      </Docs>
    </Member>
  </Members>
</Type>
