<?xml version="1.0" encoding="utf-8"?>
<xliff xmlns="urn:oasis:names:tc:xliff:document:1.2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.2" xsi:schemaLocation="urn:oasis:names:tc:xliff:document:1.2 xliff-core-1.2-transitional.xsd">
  <file datatype="xml" original="TerminateWorkflow.xml" source-language="en-US" target-language="de-DE">
    <header>
      <tool tool-id="mdxliff" tool-name="mdxliff" tool-version="1.0-15c36f0" tool-company="Microsoft" />
      <xliffext:skl_file_name xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">02cd5861-7ce2-4a82-b358-31f8435a0ac5212968e3d67251595f9eb943ad43201b8a60a5a5.skl</xliffext:skl_file_name>
      <xliffext:version xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">1.2</xliffext:version>
      <xliffext:ms.openlocfilehash xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">212968e3d67251595f9eb943ad43201b8a60a5a5</xliffext:ms.openlocfilehash>
      <xliffext:ms.sourcegitcommit xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">d31dc2ede16f6f7bc64e90d9f897ff54c4e3869b</xliffext:ms.sourcegitcommit>
      <xliffext:ms.lasthandoff xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">04/03/2018</xliffext:ms.lasthandoff>
      <xliffext:moniker_ids xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">netframework-4.5.1,netframework-4.5.2,netframework-4.5,netframework-4.6.1,netframework-4.6.2,netframework-4.6,netframework-4.7.1,netframework-4.7</xliffext:moniker_ids>
    </header>
    <body>
      <group id="content" extype="content">
        <trans-unit id="101" translate="yes" xml:space="preserve" uid="T:System.Activities.Statements.TerminateWorkflow">
          <source>Terminates the running workflow instance, raises the <ph id="ph1">&lt;see cref="P:System.Activities.WorkflowApplication.Completed" /&gt;</ph> event in the host, and reports error information.</source>
          <target state="translated">Beendet die ausgeführte Workflowinstanz, löst das <ph id="ph1">&lt;see cref="P:System.Activities.WorkflowApplication.Completed" /&gt;</ph>-Ereignis auf dem Host aus und meldet Fehlerinformationen.</target>       </trans-unit>
        <trans-unit id="102" translate="yes" xml:space="preserve" uid="T:System.Activities.Statements.TerminateWorkflow">
          <source>Once the workflow is terminated, it cannot be resumed.</source>
          <target state="translated">Ein einmal beendeter Workflow kann nicht fortgesetzt werden.</target>       </trans-unit>
        <trans-unit id="103" translate="yes" xml:space="preserve" uid="M:System.Activities.Statements.TerminateWorkflow.#ctor">
          <source>Creates a new instance of the <ph id="ph1">&lt;see cref="T:System.Activities.Statements.TerminateWorkflow" /&gt;</ph> class.</source>
          <target state="translated">Erstellt eine neue Instanz der <ph id="ph1">&lt;see cref="T:System.Activities.Statements.TerminateWorkflow" /&gt;</ph>-Klasse.</target>       </trans-unit>
        <trans-unit id="104" translate="yes" xml:space="preserve" uid="P:System.Activities.Statements.TerminateWorkflow.Exception">
          <source>Gets or sets the exception that provoked the instance termination.</source>
          <target state="translated">Ruft die Ausnahme ab, die die Instanzbeendigung ausgelöst hat, oder legt sie fest.</target>       </trans-unit>
        <trans-unit id="105" translate="yes" xml:space="preserve" extradata="MT" uid="P:System.Activities.Statements.TerminateWorkflow.Exception">
          <source>The exception.</source>
          <target state="translated">Die Ausnahme.</target>       </trans-unit>
        <trans-unit id="106" translate="yes" xml:space="preserve" extradata="MT" uid="P:System.Activities.Statements.TerminateWorkflow.Exception">
          <source>The exception that is passed to <ph id="ph1">&lt;xref:System.Activities.WorkflowApplication.Terminate%2A&gt;</ph> is a <ph id="ph2">&lt;xref:System.Activities.WorkflowApplicationTerminatedException&gt;</ph> if only <ph id="ph3">&lt;xref:System.Activities.Statements.TerminateWorkflow.Reason%2A&gt;</ph> is set.</source>
          <target state="translated">Die Ausnahme, die an <ph id="ph1">&lt;xref:System.Activities.WorkflowApplication.Terminate%2A&gt;</ph> übergeben wird, ist eine <ph id="ph2">&lt;xref:System.Activities.WorkflowApplicationTerminatedException&gt;</ph>, wenn nur <ph id="ph3">&lt;xref:System.Activities.Statements.TerminateWorkflow.Reason%2A&gt;</ph> festgelegt wird.</target>       </trans-unit>
        <trans-unit id="107" translate="yes" xml:space="preserve" extradata="MT" uid="P:System.Activities.Statements.TerminateWorkflow.Exception">
          <source>If only <ph id="ph1">&lt;xref:System.Activities.Statements.TerminateWorkflow.Exception%2A&gt;</ph> is set, that exception is passed to <ph id="ph2">&lt;xref:System.Activities.WorkflowApplication.Terminate%2A&gt;</ph>.</source>
          <target state="translated">Wird nur <ph id="ph1">&lt;xref:System.Activities.Statements.TerminateWorkflow.Exception%2A&gt;</ph> festgelegt, wird diese Ausnahme an <ph id="ph2">&lt;xref:System.Activities.WorkflowApplication.Terminate%2A&gt;</ph> übergeben.</target>       </trans-unit>
        <trans-unit id="108" translate="yes" xml:space="preserve" extradata="MT" uid="P:System.Activities.Statements.TerminateWorkflow.Exception">
          <source>If both <ph id="ph1">&lt;xref:System.Activities.Statements.TerminateWorkflow.Reason%2A&gt;</ph> and <ph id="ph2">&lt;xref:System.Activities.Statements.TerminateWorkflow.Exception%2A&gt;</ph> are set, a <ph id="ph3">&lt;xref:System.Activities.WorkflowApplicationTerminatedException&gt;</ph> is passed with the specified <ph id="ph4">&lt;xref:System.Activities.Statements.TerminateWorkflow.Reason%2A&gt;</ph>, and <ph id="ph5">&lt;xref:System.Activities.Statements.TerminateWorkflow.Exception%2A&gt;</ph> is set as the exception’s <ph id="ph6">&lt;xref:System.Exception.InnerException%2A&gt;</ph> property.</source>
          <target state="translated">Werden sowohl <ph id="ph1">&lt;xref:System.Activities.Statements.TerminateWorkflow.Reason%2A&gt;</ph> als auch <ph id="ph2">&lt;xref:System.Activities.Statements.TerminateWorkflow.Exception%2A&gt;</ph> festgelegt, wird eine <ph id="ph3">&lt;xref:System.Activities.WorkflowApplicationTerminatedException&gt;</ph> mit dem angegebenen <ph id="ph4">&lt;xref:System.Activities.Statements.TerminateWorkflow.Reason%2A&gt;</ph> Grund übergeben, und <ph id="ph5">&lt;xref:System.Activities.Statements.TerminateWorkflow.Exception%2A&gt;</ph> wird als <ph id="ph6">&lt;xref:System.Exception.InnerException%2A&gt;</ph>-Eigenschaft der Ausnahme festgelegt.</target>       </trans-unit>
        <trans-unit id="109" translate="yes" xml:space="preserve" extradata="MT" uid="P:System.Activities.Statements.TerminateWorkflow.Exception">
          <source>If neither is set, a default <ph id="ph1">&lt;xref:System.Activities.WorkflowApplicationTerminatedException&gt;</ph> is created.</source>
          <target state="translated">Erfolgt keine Festlegung, wird eine standardmäßige <ph id="ph1">&lt;xref:System.Activities.WorkflowApplicationTerminatedException&gt;</ph> erstellt.</target>       </trans-unit>
        <trans-unit id="110" translate="yes" xml:space="preserve" uid="P:System.Activities.Statements.TerminateWorkflow.Reason">
          <source>A string input argument with the reason for the workflow instance termination.</source>
          <target state="translated">Ein Zeichenfolgeneingabeargument mit dem Grund für die Beendigung der Workflowinstanz.</target>       </trans-unit>
        <trans-unit id="111" translate="yes" xml:space="preserve" extradata="MT" uid="P:System.Activities.Statements.TerminateWorkflow.Reason">
          <source>The reason for workflow termination.</source>
          <target state="translated">Der Grund für die Workflowbeendigung.</target>       </trans-unit>
        <trans-unit id="112" translate="yes" xml:space="preserve" extradata="MT" uid="P:System.Activities.Statements.TerminateWorkflow.Reason">
          <source>The exception that is passed to <ph id="ph1">&lt;xref:System.Activities.WorkflowApplication.Terminate%2A&gt;</ph> is a <ph id="ph2">&lt;xref:System.Activities.WorkflowApplicationTerminatedException&gt;</ph> if only <ph id="ph3">&lt;xref:System.Activities.Statements.TerminateWorkflow.Reason%2A&gt;</ph> is set.</source>
          <target state="translated">Die Ausnahme, die an <ph id="ph1">&lt;xref:System.Activities.WorkflowApplication.Terminate%2A&gt;</ph> übergeben wird, ist eine <ph id="ph2">&lt;xref:System.Activities.WorkflowApplicationTerminatedException&gt;</ph>, wenn nur <ph id="ph3">&lt;xref:System.Activities.Statements.TerminateWorkflow.Reason%2A&gt;</ph> festgelegt wird.</target>       </trans-unit>
        <trans-unit id="113" translate="yes" xml:space="preserve" extradata="MT" uid="P:System.Activities.Statements.TerminateWorkflow.Reason">
          <source>If only <ph id="ph1">&lt;xref:System.Activities.Statements.TerminateWorkflow.Exception%2A&gt;</ph> is set, that exception is passed to <ph id="ph2">&lt;xref:System.Activities.WorkflowApplication.Terminate%2A&gt;</ph>.</source>
          <target state="translated">Wird nur <ph id="ph1">&lt;xref:System.Activities.Statements.TerminateWorkflow.Exception%2A&gt;</ph> festgelegt, wird diese Ausnahme an <ph id="ph2">&lt;xref:System.Activities.WorkflowApplication.Terminate%2A&gt;</ph> übergeben.</target>       </trans-unit>
        <trans-unit id="114" translate="yes" xml:space="preserve" extradata="MT" uid="P:System.Activities.Statements.TerminateWorkflow.Reason">
          <source>If both <ph id="ph1">&lt;xref:System.Activities.Statements.TerminateWorkflow.Reason%2A&gt;</ph> and <ph id="ph2">&lt;xref:System.Activities.Statements.TerminateWorkflow.Exception%2A&gt;</ph> are set, a <ph id="ph3">&lt;xref:System.Activities.WorkflowApplicationTerminatedException&gt;</ph> is passed with the specified <ph id="ph4">&lt;xref:System.Activities.Statements.TerminateWorkflow.Reason%2A&gt;</ph>, and <ph id="ph5">&lt;xref:System.Activities.Statements.TerminateWorkflow.Exception%2A&gt;</ph> is set as the exception’s <ph id="ph6">&lt;xref:System.Exception.InnerException%2A&gt;</ph> property.</source>
          <target state="translated">Werden sowohl <ph id="ph1">&lt;xref:System.Activities.Statements.TerminateWorkflow.Reason%2A&gt;</ph> als auch <ph id="ph2">&lt;xref:System.Activities.Statements.TerminateWorkflow.Exception%2A&gt;</ph> festgelegt, wird eine <ph id="ph3">&lt;xref:System.Activities.WorkflowApplicationTerminatedException&gt;</ph> mit dem angegebenen <ph id="ph4">&lt;xref:System.Activities.Statements.TerminateWorkflow.Reason%2A&gt;</ph> Grund übergeben, und <ph id="ph5">&lt;xref:System.Activities.Statements.TerminateWorkflow.Exception%2A&gt;</ph> wird als <ph id="ph6">&lt;xref:System.Exception.InnerException%2A&gt;</ph>-Eigenschaft der Ausnahme festgelegt.</target>       </trans-unit>
        <trans-unit id="115" translate="yes" xml:space="preserve" extradata="MT" uid="P:System.Activities.Statements.TerminateWorkflow.Reason">
          <source>If neither is set, a default <ph id="ph1">&lt;xref:System.Activities.WorkflowApplicationTerminatedException&gt;</ph> is created.</source>
          <target state="translated">Erfolgt keine Festlegung, wird eine standardmäßige <ph id="ph1">&lt;xref:System.Activities.WorkflowApplicationTerminatedException&gt;</ph> erstellt.</target>       </trans-unit>
      </group>
    </body>
  </file>
</xliff>